litmuschaos/chaos-runner

- bin/exec.go
- pkg/utils/configMapUtils.go
- pkg/utils/secretsUtils.go
- pkg/utils/volumeUtils.go
- pkg/utils/watchJob.go
- This PR, will add the ability to validate Secrets, in the application namespace, and add those into the Job created.
- Unlike ConfigMap validation, it will not create the secrets, on its own.
https://github.com/litmuschaos/chaos-executor/issues/13
**Checklist:**
> [Feat] Validation of Secrets pre-created in Application Namespace

- pkg/utils/types.go
This PR is for this issue: https://github.com/litmuschaos/chaos-executor/issues/20
Logs:
```
chaos:~$ kubectl logs -f engine-runner -n litmus
W0102 11:33:25.919087       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-01-02T11:33:25Z" level=info msg="Experiments List:  [pod-delete]   Engine Name:  engine   appLabels :  app=nginx   appNamespace:  litmus   appKind:     Service Account Name:  litmus" …
```
> [Fix(Issue#20)] chaos-executor: Fixed creation of clientSet

- bin/exec.go
Signed-off-by: chandan kumar <chandan.kr404@gmail.com>
- Update the experiment name passed to google analytics, i.e: pass the experiment name instead of passing the experiment name with the random generated string
**Checklist:**
> (fix): Update the experiment name passed to google analytics

- pkg/utils/experimentHelpers.go
- pkg/utils/getOSenv.go
- pkg/utils/types.go
- Adding AuxiliaryAppInfo field and pass this as an ENV in chaos Job.
- The auxiliaryAppInfo contains the namespace and labels of all the dependent applications in infra-chaos experiment. Sample auxiliaryAppInfo ns1:name=percona,ns2:run=nginx
- This field is used to check the health status of all the auxiliary application in the Pre and Post chaos checks.
**Logs**
[without-auxiliaryAppinfo.txt](https://github.com/litmuschaos/chaos-executor/files/4057774/without-auxiliaryAppinfo.txt)
[withauxiliaryAppinfo.txt](https://github.com/litmuschaos/chaos-executor/files/4057775/withauxiliaryAppinfo.txt)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …
> (feat): Add auxiliaryAppInfo in go-executor

- bin/runner.go
- pkg/utils/recorder.go
- pkg/utils/types.go
- Adds a blanket event signifying runners failure to create the experiment job. 
- https://github.com/litmuschaos/chaos-runner/issues/54
**Checklist:**
> (feat) Added Event of ChaosEngine for Skipped Experiments

- pkg/utils/recorder.go
- In this PR, fixed the name of the components shown in chaosengine events.
https://github.com/litmuschaos/litmus/issues/1326
**Checklist:**
> (fix) Added name of the runner Pod in ChaosEngine Events

- bin/runner.go
- pkg/utils/experimentHelpers.go
- pkg/utils/getOSenv.go
- pkg/utils/initialPatchEngine.go
- pkg/utils/types.go
- pkg/utils/watchJob.go
- Replaced EngineDetails.AppNamespace to EngineDetails.EngineNamespace
- Added logic to check for resources in chaosEngine namespace
- Added OS ENV as CHAOS_NAMESPACE passed from operator, into engineDetails struct
- EngineDetails.EngineNamespace will always keep experiment.Namespace in sync
- All job related resources(job,configmaps,secrets etc) will be  in AppNamespace (experiment.Namespace)
- All engine related resources will be in EngineNamespace(engineDetails.EngineNamespace)
- Added OS ENV as CHAOS_NAMESPACE passed from operator, into engineDetails struct
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when …
> (feat) Added support for AdminMode

- pkg/utils/experimentHelpers.go
- Rename Engine_NAMESPACE to CHAOS_NAMESPACE
**Checklist:**
> refactor(chaos_ns): Rename Engine_NAMESPACE to CHAOS_NAMESPACE

- bin/runner.go
- pkg/utils/experimentHelpers.go
- pkg/utils/initialPatchEngine.go
- pkg/utils/status.go
- This PR is in accordance with the creation if multiple ChaosEngine.ExperimentStatues
- The bug was that, it was not able to get the jobName until that experiment is executed (ex: pod-delete and container-kill), it would create 2 statuses for pod-delete, and then when container-kill started, it created 2 more.
- To fix that i patched initial status before we start with experiments.
- TO that I created a list of ExperimentDetails struct, filled in values for all experiments using engineDetails.
-  Then created the initial status
-  After that went ahead to iterate over it.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that …
> (fix) Creation of Multiple ExperimentStatuses fixed

- build/Dockerfile
Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>
- This PR is for addition of user_id in the Dockerfile of chaos-runner to run it as non root user.
A GitLab run with the given changes in the image: https://gitlab.mayadata.io/litmuschaos/litmus-e2e/pipelines/12501
**Checklist:**
> chore(Dockerfile): Add user_id in the Dockerfile of chaos-runner

- vendor/github.com/litmuschaos/chaos-operator/pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- For the continuous probe an extra variable is required in run properties. It contains the time interval for which we have to wait after each iteration of the continuous probe.
**Checklist:**
> chore(continuous-probe): Adding the continuous probes in go experiments

- pkg/utils/watchChaosContainer.go
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
- This PR is for fixing the issue when a chaos experiment Is unable to come in running state the runner was continuously checking for the experiment status. 
- In cases where the experiment job creation is unsuccessful, the runner skips the experiment with right error. 
**Checklist:**
> fix(timeout): Add timeout when the chaos experiment fails to come in running state

- pkg/utils/builders.go
- pkg/utils/engineHelper.go
- pkg/utils/environment.go
- pkg/utils/experimentHelper.go
- pkg/utils/types.go
- pkg/utils/watchJob.go
- tests/runner_test.go
Fixes litmuschaos/litmus#2368
Previously, ENVs can only use plain text.
This patch allows to use corev1.EnvVar at CR schema so that it can get value from secret/configmap/downwardAPI.
- Refactored some receiver/variable names to be consistent
- Used for-range values instead of using indices
Signed-off-by: kazukousen <mmchari.0228@gmail.com>
> Move ENVs to corev1.EnvVar instead of custom struct

- pkg/utils/volumeUtils.go
- If configmaps was not defined, it was returning nil volumeopts instance, which was creating a problem if configmap is not defined but secrets is defined as builder received a nil instance for the secrets and it's tried to access `volumeopts.VolumeBuilders` which was causing an issue.
**Checklist:**
> chore(volumes): fix the volume builder operations

- go.mod
- go.sum
- pkg/utils/builders.go
- pkg/utils/engineHelper.go
- pkg/utils/environment.go
- pkg/utils/types.go
- tests/runner_test.go
- vendor/github.com/litmuschaos/chaos-operator/pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- vendor/github.com/litmuschaos/chaos-operator/pkg/apis/litmuschaos/v1alpha1/chaosexperiment_types.go
- vendor/github.com/litmuschaos/chaos-operator/pkg/apis/litmuschaos/v1alpha1/chaosresult_types.go
- vendor/github.com/litmuschaos/elves/kubernetes/podtemplatespec/podtemplatespec.go
- vendor/modules.txt
Signed-off-by: shubhamchaudhary <shubham@chaosnative.com>
- Adding support for the termination grace period seconds of the experiment & helper pod. Which can be provided at `.spec.experiments[*].spec.components.terminationGracePeriodSeconds` path inside chaosengine.
**Checklist:**
> chore(terminationGracePeriodSeconds): Add support for termination grace period seconds

- .circleci/config.yml
- tests/runner_test.go
- Puts an upper time limit for BDD runs 
- Removes CRD deletion step as a new feature in operator looks for chaosresults and if it needs to be patched with any info (esp. for abort of engine deletion cases)
**Checklist:**
> (chore)ci: upper higher run time for bdd

- bin/runner.go
- pkg/utils/environment.go
- pkg/utils/watchJob.go
Signed-off-by: shubhamchaudhary <shubham@chaosnative.com>
-  Marked default jobCleanupPolicy policy as retain
- updated the env getter function
**Checklist:**
> chore(env): updated the env getter function & default jobCleanUpPolicy as retain

- build/Dockerfile
Signed-off-by: uditgaurav <udit@chaosnative.com>
Package vcs exposes functions for resolving import paths and using version control systems, which can be used to implement behavior similar to the standard "go get" command.
Error:
```bash
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: missing Git command. See https://golang.org/s/gogetcmd
error obtaining VCS status: exec: "git": executable file not found in $PATH
Use -buildvcs=false to disable VCS stamping.
The command '/bin/sh -c CGO_ENABLED=0 go build -o /output/chaos-runner -v ./bin' returned a non-zero code: 1
```
Can be fixed by using: `go build -buildvcs=false -o /output/chaos-runner -v ./bin`  (-buildvcs=false flag)
**Which issue this PR fixes** …
> Chore(build): Fix the go build by providing -buildvcs=false flag

- go.mod
- go.sum
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
This PR updates chaos operator pkg to support `resourceNames` field in k8sprobe
Related https://github.com/litmuschaos/litmus-go/issues/599
**Checklist:**
> feat: update chaos operator pkg

- pkg/utils/engineHelper.go
Signed-off-by: Shubham Chaudhary <shubham.chaudhary@harness.io>
**Checklist:**
> chore(engine): Adding chaosengine labels to experiment pod

- build/Dockerfile
Migrate the base images of the chaos-runner container images of LitmusChaos from infra-alpine to ubi minimal.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4634  (https://github.com/litmuschaos/litmus/issues/4634)
**Checklist:**
> UBI migration of Images - chaos-runner
