- .circleci/config.yml
- Makefile
- build/push
Signed-off-by: chandan kumar <chandan.kr404@gmail.com>
> (build): Setup the build workflow

- README.md
Signed-off-by: ksatchit <ksatchit@mayadata.io>
**Checklist:**
> (chore)add readme

- Makefile
- bin/exec.go
- pkg/utils/builders.go
- pkg/utils/configMapUtils.go
- pkg/utils/expNotFoundPatch.go
- pkg/utils/experimentHelpers.go
- pkg/utils/initialPatchEngine.go
- pkg/utils/secretsUtils.go
- pkg/utils/status.go
- pkg/utils/volumeUtils.go
- pkg/utils/watchJob.go
> [chore] Refactoring of Codebase

- .circleci/config.yml
Signed-off-by: ksatchit <ksatchit@mayadata.io>
- Fixes a typo in the circle ci config to enable tagged images
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #26 
**Checklist:**
> (fix)typo in circle ci config

- README.md
> (chore) Added GoReport Card, and BCH Card in README.md

- .circleci/config.yml
- README.md
Signed-off-by: ksatchit <ksatchit@mayadata.io>
- (fix)typo in circle ci config #27 
- (chore) Added GoReport Card, and BCH Card in README.md #28
> [Cherry-pick for RC2]

- pkg/utils/experimentHelpers.go
- pkg/utils/getOSenv.go
- pkg/utils/types.go
> [Cherry pick into v1.0.x for GA] 

- README.md
> (feat) Added DockerPull Count in README.md

- pkg/utils/experimentHelpers.go
- Updating the engienUID label's key to chaosUID 
**Checklist:**
> (refactor): Updated engineUID to chaosUID

- bin/runner.go
- pkg/utils/analytics/analytics.go
- pkg/utils/builders.go
- pkg/utils/configMapUtils.go
- pkg/utils/secretsUtils.go
- pkg/utils/status.go
- This PR addresses misspelled keywords across chaos-runner.
**Checklist:**
> (fix) Fixed misspelled keywords

- pkg/utils/builders.go
- Adding steps to get job-pod name using downward API
- We are passing the POD_NAME env into `chaos-experiment-job-pod` using downward api because it will be created dynamically i.e, `pod-delete-gfgfg-gdhdj`. Events need the name of the resources which generated those events.
**Checklist:**
> feat(downwardAPI): Adding steps to get job-pod name using downward api

- pkg/utils/watchJob.go
- Ensures the default jobCleanupPolicy is set to "delete"
**Checklist:**
> (chore) Changed DefaultMode of Job Deletion as Always

- Gopkg.lock
- bin/runner.go
- pkg/utils/experimentHelpers.go
- pkg/utils/recorder.go
- pkg/utils/types.go
- pkg/utils/watchJob.go
- vendor/github.com/golang/groupcache/LICENSE
- vendor/github.com/golang/groupcache/lru/lru.go
- vendor/k8s.io/apimachinery/pkg/util/mergepatch/errors.go
- vendor/k8s.io/apimachinery/pkg/util/mergepatch/util.go
- vendor/k8s.io/apimachinery/pkg/util/strategicpatch/errors.go
- vendor/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go
- vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go
- vendor/k8s.io/apimachinery/pkg/util/strategicpatch/types.go
- vendor/k8s.io/apimachinery/third_party/forked/golang/json/fields.go
- vendor/k8s.io/client-go/tools/record/doc.go
- vendor/k8s.io/client-go/tools/record/event.go
- vendor/k8s.io/client-go/tools/record/events_cache.go
- vendor/k8s.io/client-go/tools/record/fake.go
- vendor/k8s.io/client-go/tools/record/util/util.go
- vendor/k8s.io/kube-openapi/pkg/util/proto/doc.go
- vendor/k8s.io/kube-openapi/pkg/util/proto/document.go
- vendor/k8s.io/kube-openapi/pkg/util/proto/openapi.go
- Added EventBroadcaster via client-go
- Added all functions in recorder.go
- Added a global structure for Recorder, with EventResource as the ChaosEngine
TODO:
- Replacing recorder object passing with its refernce
- Tryout approach for ExperimentSkipped Event
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # https://github.com/litmuschaos/litmus/issues/1243
**Checklist:**
> (feat) Addition of events in Chaos-Runner

- NOTICE.md
Signed-off-by: ksatchit <ksatchit@mayadata.io>
- Add a license notice 
**Checklist:**
> (chore)notice: add license notice

- NOTICE.md
- README.md
- bin/runner.go
- pkg/utils/recorder.go
- pkg/utils/types.go
- Includes the following commits: 
- https://github.com/litmuschaos/chaos-runner/commit/8762a2912fba79b34c97d6727e1ed1d55951b083
- https://github.com/litmuschaos/chaos-runner/commit/716f52b3fb6cbfd1d5d92401ce340cddde01b2f8
- https://github.com/litmuschaos/chaos-runner/commit/5040c28a825fe7153b2e7ad3b5fe42db305a90ff
**Checklist:**
> [Cherry pick for 1.2.0]

- bin/runner.go
- pkg/utils/experimentHelpers.go
- pkg/utils/getOSenv.go
- pkg/utils/initialPatchEngine.go
- pkg/utils/recorder.go
- pkg/utils/types.go
- pkg/utils/watchJob.go
- (fix) Added name of the runner Pod in ChaosEngine Events (#56) …
- (feat) Added support for AdminMode (#45) …
- refcator(chaos_ns): Rename Engine_NAMESPACE to CHAOS_NAMESPACE (#57) …
**Checklist:**
> [Cherry pick for 1.2.2] 

- tests/runner_test.go
- Removes checks for creation of monitor/exporter pods in BDD test
**Checklist:**
> (fix)bdd: remove checks for monitor pods

- .circleci/config.yml
- pkg/utils/experimentHelpers.go
Signed-off-by: Raj <raj.das@mayadata.io>
Adding trivy security check to circle ci
https://github.com/litmuschaos/litmus/issues/322
**Checklist:**
> (feat): Adding trivy security check to circle ci

- tests/runner_test.go
> (fix)bdd : Fixed BDD URL issues

- .circleci/config.yml
- tests/runner_test.go
Cherry-picked commit:
- (fix)bdd: remove checks for monitor pods (#61) …
- (feat): Adding trivy security check to circle ci (#58) …
- (fix) Fixed BDD URL issues (#64) …
> Cherry-pick for v1.3.x

- pkg/utils/builders.go
- pkg/utils/experimentHelpers.go
- pkg/utils/types.go
- vendor/github.com/litmuschaos/chaos-operator/pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- vendor/github.com/litmuschaos/elves/kubernetes/job/build.go
Addressing issue mentioned at https://github.com/litmuschaos/litmus/issues/1421 for chaos-runner changes
https://github.com/litmuschaos/litmus/issues/1421
**Checklist:**
> Updating chaos runner for https://github.com/litmuschaos/litmus/issues/1421

- bin/runner.go
- go.mod
- go.sum
- pkg/utils/types.go
- pkg/utils/watchChaosContainer.go
- pkg/utils/watchJob.go
> feat(istio): Adding support to run in istio enabled mode

- vendor/github.com/litmuschaos/chaos-operator/pkg/apis/litmuschaos/v1alpha1/chaosresult_types.go
> update(chaosresult): Updating the chaosresult_types.go file

- pkg/utils/builders.go
- The Pod is restarted repeatedly for the failure cases
**Checklist:**
> update(chaos-pod): Changing the restart policy of chaos-pod

- pkg/utils/builders.go
- vendor/github.com/litmuschaos/chaos-operator/pkg/apis/litmuschaos/v1alpha1/chaosresult_types.go
https://github.com/litmuschaos/chaos-runner/pull/82/commits/f879b5cb9d256da40f08581da96f605d3d47d655
https://github.com/litmuschaos/chaos-runner/pull/82/commits/d90abb9a7319b93ec5518cb87517573c9a3f2fa4
**Checklist:**
> [Cherry-pick for 1.7.0]

- CONTRIBUTING.md
- README.md
> chore(contribution-guide): Adding the contribution-guide in chaos-runner

- pkg/utils/experimentHelpers.go
- pkg/utils/types.go
- pkg/utils/watchJob.go
> chore(chaos-result): appending the instance_id in the chaos-result name

- pkg/utils/experimentHelpers.go
- Passing experiment name from chaos-runner as env
**Checklist:**
> chore(exp-name): Passing experiment name from chaos-runner as env

- .circleci/config.yml
- Makefile
- Update the image tags for dev branch
**Checklist:**
> (chore)build: update image tags for dev branch

- pkg/utils/experimentHelpers.go
> fix(timeout): fixing the timeout for pending state

- .circleci/config.yml
- Makefile
- build/Dockerfile
- build/go-multiarch-build.sh
- build/push
- pkg/utils/watchChaosContainer.go
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
**Checklist:**
> chore(add): Add multiarch image into master chaos-runner

- .circleci/config.yml
- Makefile
- build/Dockerfile
- build/go-multiarch-build.sh
- build/push
- pkg/utils/watchChaosContainer.go
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
https://github.com/litmuschaos/chaos-runner/pull/112/commits/fe34a7b786268000b803611ee9b184f2bf525b7a
**Checklist:**
> [Cherry Pick for v1.10.x]

- pkg/utils/experimentHelpers.go
- pkg/utils/getOSenv.go
- pkg/utils/types.go
> chore(annotation): multi app annotation support

- Makefile
- pkg/utils/experimentHelpers.go
- pkg/utils/types.go
> chore(jobcleanup): Delete the helper pod based on jobCleanupPolicy

- build/Dockerfile
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
**Checklist:**
> chore(image): Reduce image size of runner

- pkg/utils/experimentHelpers.go
> chore(imagePullPolicy): passing libImagePullPolicy env to exp job

- pkg/utils/volumeUtils.go
> [Cherry-pick for 1.11.1]

- pkg/utils/event.go
> chore(events): update event message with increment

- pkg/utils/event.go
> [Cherry-pick for 1.11.2]

- go.mod
- go.sum
- vendor/github.com/litmuschaos/chaos-operator/pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- vendor/modules.txt
> (chore)vendor: update vendor based on latest changes to chaos operator

- go.mod
- go.sum
- vendor/github.com/litmuschaos/chaos-operator/pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- vendor/modules.txt
> [Cherry-pick for v1.11.3]

- build/push
https://github.com/litmuschaos/chaos-runner/pull/131/commits/836b1197ac521b45cf092ac78ddeaac20481663e
**Checklist:**
> [Cherry-pick for 1.12.2]

- pkg/utils/environment.go
> feat(imagePullPolicy): Passing the LIBImagePullPolicy ENV to the experiment pod

- go.mod
- go.sum
- pkg/utils/builders.go
- pkg/utils/engineHelper.go
- pkg/utils/environment.go
- pkg/utils/types.go
- tests/runner_test.go
- vendor/github.com/litmuschaos/chaos-operator/pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- vendor/github.com/litmuschaos/chaos-operator/pkg/apis/litmuschaos/v1alpha1/chaosexperiment_types.go
- vendor/github.com/litmuschaos/chaos-operator/pkg/apis/litmuschaos/v1alpha1/chaosresult_types.go
- vendor/github.com/litmuschaos/elves/kubernetes/podtemplatespec/podtemplatespec.go
- vendor/modules.txt
https://github.com/litmuschaos/chaos-runner/commit/97af357f7a4f462805eb498f2b22b8fe05aa4864
**Checklist:**
> [Cherry-Pick for 1.13.3]

- .circleci/config.yml
- tests/runner_test.go
> (chore)ci: upper higher run time for bdd (#142)

- go.mod
- go.sum
Signed-off-by: shubhamchaudhary <shubham@chaosnative.com>
**Checklist:**
> chore(vendors): updating the target details vendors

- pkg/utils/configMapUtils.go
- pkg/utils/initialPatchEngine.go
- pkg/utils/secretsUtils.go
- pkg/utils/watchJob.go
Signed-off-by: udit <udit@chaosnative.com>
- Print error for some error events
**Checklist:**
> Fix: Print error msg for some error events

- tests/runner_test.go
Signed-off-by: shubhamchaudhary <shubham@chaosnative.com>
- Adding retries to wait until the job creation
**Checklist:**
> fix(bdd): adding retries to wait until job creation

- pkg/utils/builders.go
- pkg/utils/experimentHelper.go
- pkg/utils/experimentHelper_test.go
- pkg/utils/types.go
> feat(command): Pass command from experiment spec to runner

- Makefile
- pkg/utils/builders.go
- pkg/utils/experimentHelper.go
- pkg/utils/experimentHelper_test.go
- pkg/utils/types.go
- tests/runner_test.go
Commits are:
- 725864c6f0bc0b018a9136226ccbc0f9c959721c
- d81b2387c84c7d1db7f42cf983e18a79b06d65b2
- 1adf15ba2acf65260851133e2db69dc026f815fa
> Cherry-Pick for 1.13.8 

- pkg/utils/watchJob.go
Signed-off-by: shubham chaudhary <shubham@chaosnative.com>
**Checklist:**
> chore(retry): adding retries for the kubeapi request

- .github/workflows/build.yml
- go.mod
- go.sum
- tests/runner_test.go
Signed-off-by: udit <udit@chaosnative.com>
**Checklist:**
> Chore(update): Update go.sum and go version to 1.17 for chaos-runner

- .github/workflows/push.yml
- .github/workflows/release.yml
Signed-off-by: udit <udit@chaosnative.com>
**Checklist:**
> Update go version to 1.17 for release build

- go.mod
- go.sum
Signed-off-by: udit <udit@chaosnative.com>
**Checklist:**
> Chore(vulnerability): Update Go mod pkgs

- .github/workflows/build.yml
Signed-off-by: uditgaurav <udit@chaosnative.com>
- Fixes snyk security scan on chaos-runner
**Checklist:**
> Chore(snyk): Fixes snyk security scan on chaos-runner

- go.mod
- go.sum
Signed-off-by: Shubham Chaudhary <shubham.chaudhary@harness.io>
**Checklist:**
> updating the go.mod for the source cmdProbe

- .github/workflows/build.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
Signed-off-by: uditgaurav <udit@chaosnative.com>
**Checklist:**
> Fix K3s cluster creation in the pipeline by providing version

- pkg/utils/environment.go
Signed-off-by: Shubham Chaudhary <shubham.chaudhary@harness.io>
**Checklist:**
> chore(env): Adding service acccount as an env

- go.mod
- go.sum
- pkg/utils/engineHelper.go
- pkg/utils/environment.go
- pkg/utils/event_test.go
- pkg/utils/types.go
> Chore(healthCheck): Update default healthCheck tunable in engine

- .github/workflows/push.yml
- Makefile
- bin/runner.go
- pkg/utils/environment.go
- pkg/utils/types.go
- pkg/utils/watchJob_test.go
- tests/runner_test.go
Signed-off-by: Shubham Chaudhary <shubham.chaudhary@harness.io>
**Checklist:**
> feat(selectors): Adding selectors inside the chaosengine

- pkg/utils/watchJob_test.go
- tests/runner_test.go
> chore(ut): fixing unit tests

- tests/runner_test.go
> fix the chaoshub fault url

- go.mod
- go.sum
> fix the go deps

- go.mod
- go.sum
- pkg/utils/builders.go
- pkg/utils/common.go
- pkg/utils/common_fuzz_test.go
- pkg/utils/experimentHelper.go
- pkg/utils/testdata/fuzz/FuzzSetWatchChaosContainerForCompletion/582528ddfad69eb5
> chore: [CHAOS-4611]: writing initial fuzz testing for chaos runner

- pkg/utils/builders_fuzz_test.go
> test: Adding fuzz test for getEnvFromMap in builders.go

- pkg/utils/builders_fuzz_test.go
- pkg/utils/testdata/fuzz/FuzzSetSidecarSecrets/582528ddfad69eb5
> test: Adding fuzz test for getSetSidecarSecrets in builders.go

- pkg/utils/builders_fuzz_test.go
> chore: [CHAOS-4699]: added fuzz test for FuzzBuildContainerSpec

- README.md
> Remove BCH banner from readme
